name: Deploy to S3

on:
  pull_request:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1 

    - name: Upload src to S3
      run: aws s3 sync src/ s3://static-portfolio-bucket/projects/ui-dev/kribb-ui/ --delete  --exclude ".github/*"